kind: pipeline
name: react-ci-cd

steps:
  - name: deps
    image: node:alpine
    commands:
      - npm install
  - name: build
    image: node:alpine
    commands:
      - npm run build
  - name: test
    image: node:alpine
    commands:
      - npm test
  - name: pre-release
    image: node:alpine
    commands:
      - tar -zcvf build.tar.gz build/
    when:
        event: tag
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - build.tar.gz
    when:
      event: tag
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: drone-thomasdebacker
    when:
      status: [ success, failure ]